spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/plbk
    username: plbk
    password: plbk
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-dev.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    root: INFO
    pro.itfray: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
