spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-dev.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:15432/plbk?currentSchema=plbk}
    username: ${DATASOURCE_USERNAME:plbk}
    password: ${DATASOURCE_PASSWORD:plbk}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-secret: ${KEYCLOAK_CLIENT_SECRET:LbLkIIODlKOPM1inpn9um9rYQGk9NLMAzoCRiEHB8wdRhmaRFWhRV4JC4vozz2JbdFzgAfVl5T4dgYD2ifU9WV}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18081/realms/pool-booking}

logging:
  level:
    root: INFO
    pro.itfray: DEBUG
