spring:
  devtools:
    add-properties: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-dev.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:15432/plbk?currentSchema=plbk}
    username: ${DATASOURCE_USERNAME:plbk}
    password: ${DATASOURCE_PASSWORD:plbk}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:18081/realms/pool-booking/protocol/openid-connect/certs}

logging:
  level:
    root: INFO
    pro.itfray: DEBUG
